name: Build & Push Container Image
on:
  push:
    branches:
    - master
    tags:
    - refs/tags/*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker.io/vshn/steward:${{ github.ref }}
    steps:
    - uses: actions/checkout@v1
    - name: Build Image
      run: make docker
    - name: Push Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${IMAGE_NAME}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
